docs/vendors.md
=> add docs directory back

.github/workflows/build-marketplace.yml, .github/workflows/run-vendor-validation.yml, adoptium-marketplace-server/adoptium-repo/docker/Dockerfile, docker/Dockerfile, docker/Dockerfile.marketplace
draft until https://github.com/adoptium/marketplace-api.adoptium.net/pull/16 has been merged
=> bump Temurin to JDK21

.github/workflows/deploy-marketplace.yml
@johnoliver we'll need to rename the `marketplace-updater-api` deployments to `updater-api` for this script to work
=> add automated deploy script

.github/workflows/build-marketplace.yml
=> Skip cache until we can prove stability

adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-frontend/src/main/resources/application.properties, docker/run.sh
Copied from https://github.com/adoptium/api.adoptium.net/pull/655
=> Fix deprecated settings

.github/workflows/deploy-marketplace.yml
=> Cancel deployments if a new commit is merged

adoptium-marketplace-schema/src/main/java/net/adoptium/marketplace/schema/OpenjdkVersionData.java
=> Switch LTS schedule to match 2-year

.github/workflows/build-marketplace.yml, .github/workflows/run-vendor-validation.yml
=> cache maven packages as part of cache mechanism

.github/actions/build-marketplace/action.yml
=> add working directory to reusable action

adoptium-marketplace-utils/src/test/kotlin/ExtractAdoptiumReleases.kt, adoptium-marketplace-utils/src/test/kotlin/ExtractIbmReleases.kt, adoptium-marketplace-utils/src/test/kotlin/ExtractReleases.kt
=> Merge similar Adoptium releases to prevent duplicates

adoptium-marketplace-utils/src/test/kotlin/ExtractAdoptiumReleases.kt
=> merge binary lists from multiple releases

adoptium-marketplace-server/pom.xml, adoptium-marketplace-utils/src/test/kotlin/ExtractAdoptiumReleases.kt, adoptium-marketplace-utils/src/test/kotlin/ExtractIbmReleases.kt, adoptium-marketplace-utils/src/test/kotlin/ExtractReleases.kt
=> merge main into prod

adoptium-marketplace-server/adoptium-marketplace-updater-parent/adoptium-marketplace-updater/src/test/resources/application.properties
Fix test issues probably caused by: https://github.com/quarkusio/quarkus/issues/38390
=> Fix test issues with quarkus updates

adoptium-marketplace-schema/src/main/resources/META-INF/beans.xml, adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-frontend/src/main/kotlin/net/adoptium/marketplace/server/frontend/routes/AssetsResource.kt, adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-frontend/src/main/kotlin/net/adoptium/marketplace/server/frontend/routes/VendorStatusRoute.kt, adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-frontend/src/main/kotlin/net/adoptium/marketplace/server/frontend/routes/info/AvailableReleasesResource.kt, adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-frontend/src/main/kotlin/net/adoptium/marketplace/server/frontend/routes/info/ReleaseListResource.kt, adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-frontend/src/main/resources/application.properties
Seems recent Quarkus releases do not play well with kotlin suspend functions
=> Fix quarkus continuation issues

adoptium-marketplace-server/pom.xml, adoptium-marketplace-staging-checker/pom.xml, pom.xml
=> Fix build by bumping versions

.github/workflows/codeql.yml
=> add codeQL workflow

.github/actions/build-marketplace/action.yml, .github/workflows/build-marketplace.yml, .github/workflows/codeql.yml, .github/workflows/run-vendor-validation.yml, adoptium-marketplace-staging-checker/pom.xml
=> Remove explicit version from staging checker and remove test from validation runs

adoptium-marketplace-server/adoptium-marketplace-updater-parent/adoptium-marketplace-updater/src/test/kotlin/net/adoptium/api/UpdateTriggerTest.kt
=> Disable unreliable test

adoptium-marketplace-client/pom.xml, adoptium-marketplace-schema-tests/pom.xml, adoptium-marketplace-server/adoptium-repo/pom.xml, adoptium-marketplace-server/pom.xml, adoptium-marketplace-staging-checker/pom.xml, adoptium-marketplace-utils/pom.xml, pom.xml
=> Tidy poms and fix build errors

.github/actions/build-marketplace/action.yml
=> Allow backwards compatible validation inputs

.github/actions/build-marketplace/action.yml, .github/workflows/build-marketplace.yml, .github/workflows/codeql.yml, .github/workflows/deploy-marketplace.yml, .github/workflows/run-vendor-validation.yml, adoptium-marketplace-client/pom.xml, adoptium-marketplace-schema-tests/pom.xml, adoptium-marketplace-schema/src/main/resources/META-INF/beans.xml, adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-frontend/src/main/kotlin/net/adoptium/marketplace/server/frontend/routes/AssetsResource.kt, adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-frontend/src/main/kotlin/net/adoptium/marketplace/server/frontend/routes/VendorStatusRoute.kt, adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-frontend/src/main/kotlin/net/adoptium/marketplace/server/frontend/routes/info/AvailableReleasesResource.kt, adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-frontend/src/main/kotlin/net/adoptium/marketplace/server/frontend/routes/info/ReleaseListResource.kt, adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-frontend/src/main/resources/application.properties, adoptium-marketplace-server/adoptium-marketplace-updater-parent/adoptium-marketplace-updater/src/test/kotlin/net/adoptium/api/UpdateTriggerTest.kt, adoptium-marketplace-server/adoptium-repo/pom.xml, adoptium-marketplace-server/pom.xml, adoptium-marketplace-staging-checker/pom.xml, adoptium-marketplace-utils/pom.xml, pom.xml
=> Sync main to production (merge after #309)

adoptium-marketplace-client/src/test/java/net/adoptium/marketplace/client/Rsa256VerifierTest.java, adoptium-marketplace-client/src/test/java/net/adoptium/marketplace/client/TestServer.java, adoptium-marketplace-schema-tests/pom.xml, adoptium-marketplace-schema-tests/src/test/java/net/adoptium/marketplace/schema/SchemaTest.java, adoptium-marketplace-server/adoptium-marketplace-updater-parent/adoptium-marketplace-updater/src/test/kotlin/net/adoptium/api/UpdateRunnerNoDb.kt, adoptium-marketplace-server/adoptium-marketplace-updater-parent/adoptium-marketplace-updater/src/test/kotlin/net/adoptium/api/UpdateTriggerTest.kt, pom.xml
=> Update quarkus to 3.13.0 and fix tests/build

docker/Dockerfile
=> Convert build to multi stage build

adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-frontend/pom.xml, adoptium-marketplace-server/adoptium-marketplace-persistence/pom.xml, adoptium-marketplace-server/adoptium-marketplace-persistence/src/main/kotlin/net/adoptium/marketplace/dataSources/persitence/mongo/MongoClient.kt, adoptium-marketplace-server/adoptium-marketplace-persistence/src/main/kotlin/net/adoptium/marketplace/dataSources/persitence/mongo/MongoInterface.kt, adoptium-marketplace-server/adoptium-marketplace-persistence/src/main/kotlin/net/adoptium/marketplace/dataSources/persitence/mongo/MongoVendorPersistence.kt, adoptium-marketplace-server/adoptium-marketplace-persistence/src/main/kotlin/net/adoptium/marketplace/dataSources/persitence/mongo/codecs/DateCodecs.kt, adoptium-marketplace-server/adoptium-marketplace-persistence/src/main/kotlin/net/adoptium/marketplace/dataSources/persitence/mongo/codecs/JacksonCodecProvider.kt, adoptium-marketplace-server/adoptium-marketplace-persistence/src/main/kotlin/net/adoptium/marketplace/dataSources/persitence/mongo/codecs/ZonedDateTimeCodecProvider.kt, adoptium-marketplace-server/adoptium-marketplace-persistence/src/main/kotlin/net/adoptium/marketplace/dataSources/persitence/mongo/codecs/ZonedDateTimeCodecs.kt, adoptium-marketplace-server/adoptium-marketplace-persistence/src/test/kotlin/net/adoptium/marketplace/dataSources/persitence/mongo/MongoTest.kt, adoptium-marketplace-server/adoptium-marketplace-persistence/src/test/kotlin/net/adoptium/marketplace/dataSources/persitence/mongo/PersistenceTest.kt, adoptium-marketplace-server/adoptium-marketplace-updater-parent/adoptium-marketplace-updater/pom.xml, adoptium-marketplace-server/adoptium-marketplace-updater-parent/adoptium-marketplace-updater/src/test/kotlin/net/adoptium/api/UpdateTriggerTest.kt, adoptium-marketplace-staging-checker/pom.xml, pom.xml
=> Remove kmongo

.github/workflows/deploy-marketplace.yml
=> cleanup removed secrets

adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-frontend/pom.xml, adoptium-marketplace-server/adoptium-marketplace-updater-parent/adoptium-marketplace-updater/pom.xml, adoptium-marketplace-staging-checker/pom.xml, pom.xml
=> Bump versions

adoptium-marketplace-schema/src/main/java/net/adoptium/marketplace/schema/Asset.java, adoptium-marketplace-schema/src/main/java/net/adoptium/marketplace/schema/Binary.java, adoptium-marketplace-schema/src/main/java/net/adoptium/marketplace/schema/ImageType.java, adoptium-marketplace-schema/src/main/java/net/adoptium/marketplace/schema/IndexFile.java, adoptium-marketplace-schema/src/main/java/net/adoptium/marketplace/schema/Installer.java, adoptium-marketplace-schema/src/main/java/net/adoptium/marketplace/schema/OpenjdkVersionData.java, adoptium-marketplace-schema/src/main/java/net/adoptium/marketplace/schema/Release.java, adoptium-marketplace-schema/src/main/java/net/adoptium/marketplace/schema/SourcePackage.java, adoptium-marketplace-schema/src/main/java/net/adoptium/marketplace/schema/Vendor.java, adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-frontend-models/src/main/kotlin/net/adoptium/marketplace/server/frontend/models/BinaryAssetView.kt, adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-frontend-models/src/main/kotlin/net/adoptium/marketplace/server/frontend/models/SortMethod.kt, adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-frontend-models/src/main/kotlin/net/adoptium/marketplace/server/frontend/models/SortOrder.kt, adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-frontend/src/main/kotlin/net/adoptium/marketplace/server/frontend/routes/AssetsResource.kt, adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-frontend/src/main/kotlin/net/adoptium/marketplace/server/frontend/routes/info/ReleaseListResource.kt, adoptium-marketplace-server/adoptium-marketplace-persistence/src/main/kotlin/net/adoptium/marketplace/dataSources/ReleaseInfo.kt, adoptium-marketplace-server/adoptium-marketplace-updater-parent/adoptium-marketplace-updater/src/main/kotlin/net/adoptium/marketplace/server/updater/AdoptiumMarketplaceUpdater.kt, adoptium-marketplace-server/adoptium-repo/pom.xml, adoptium-marketplace-server/pom.xml, pom.xml
=> Dependency updates, and updates accounting for deprecated schema functions

adoptium-marketplace-schema/src/main/java/net/adoptium/marketplace/schema/Vendor.java, adoptium-marketplace-server/adoptium-marketplace-updater-parent/adoptium-marketplace-updater/src/main/kotlin/net/adoptium/marketplace/server/updater/AdoptiumMarketplaceUpdater.kt
=> Add support to remove vendors

adoptium-marketplace-utils/src/test/kotlin/ExtractAdoptiumReleases.kt
Add JDK25 as a Temurin version to extract for the marketplace
=> Add version 25 to the VERSIONS list
